### ISSUE TITLE
Use of the system

### ISSUE THREAD

**Issue by yigong837** [azreasoners/Cplus2ASP#1]
Can we only run cplus2asp through the terminal command line？

**Comment by azreasoners** [comment]
Yes, only the binary executable is provided for Cplus2ASP. You can execute shell commands with your programming language (e.g., using subprocess in Python).

**Comment by yigong837** [comment]
> Yes, only the binary executable is provided for Cplus2ASP. You can execute shell commands with your programming language (e.g., using subprocess in Python).

Ok.Is there any API plan in the future?

**Comment by azreasoners** [comment]
No, we don't plan to come back to this work in the near future.

**Comment by yigong837** [comment]
> No, we don't plan to come back to this work in the near future.

Ok,thanks.
